{% set version = "0.3.0" %}

package:
  name: pydevtool
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pydevtool/pydevtool-{{ version }}.tar.gz
  sha256: 25e3ba4f3d33ccac33ee2b9775995848d49e9b318b7a146477fb5d52f786fc8a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - doit
    - python >=3.8

test:
  imports:
    - pydevtool
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pydoit/pydevtool
  summary: CLI dev tools powered by pydoit
  dev_url: https://github.com/pydoit/pydevtool
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tupui
    - rgommers
    - schettino72
